// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: bugs.sql

package database

import (
	"context"

	"github.com/google/uuid"
)

const createBug = `-- name: CreateBug :one
INSERT INTO bugs (id, title, description, posted_by, created_at, updated_at)
VALUES (
    gen_random_uuid(),
    $1,
    $2,
    $3,
    NOW(),
    NOW()
    
)
RETURNING id, title, description, posted_by, created_at, updated_at
`

type CreateBugParams struct {
	Title       string
	Description string
	PostedBy    uuid.UUID
}

func (q *Queries) CreateBug(ctx context.Context, arg CreateBugParams) (Bug, error) {
	row := q.db.QueryRowContext(ctx, createBug, arg.Title, arg.Description, arg.PostedBy)
	var i Bug
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Description,
		&i.PostedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
