// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package database

import (
	"database/sql"
	"time"

	"github.com/google/uuid"
)

type Bug struct {
	ID          uuid.UUID
	Title       string
	Description string
	PostedBy    uuid.UUID
	CreatedAt   time.Time
	UpdatedAt   time.Time
	AssignedT0  uuid.NullUUID
	AssignedBy  uuid.NullUUID
}

type GooseDbVersion struct {
	ID        int32
	VersionID int64
	IsApplied bool
	Tstamp    time.Time
}

type RefreshToken struct {
	Token     string
	CreatedAt time.Time
	UpdatedAt time.Time
	UserID    uuid.UUID
	ExpiresAt time.Time
	RevokedAt sql.NullTime
}

type Role struct {
	ID          uuid.UUID
	Name        string
	Description sql.NullString
	CreatedAt   time.Time
}

type User struct {
	ID           uuid.UUID
	Username     string
	Email        string
	PasswordHash string
	RoleID       uuid.UUID
	CreatedAt    time.Time
	UpdatedAt    time.Time
	DeletedAt    sql.NullTime
}
