

services:

  db:
    image: postgres:16
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: bugby
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: unless-stopped

  api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      - DB_URL=postgresql://postgres:postgres@db:5432/bugby?sslmode=disable
      - PORT=8080
    # volumes:
    #   - .:/app
    entrypoint: ["/app/entrypoint.sh"]
    restart: unless-stopped

volumes:
  pgdata:

