name: Bugby-Go CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:16
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: bugby
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    env:
      DB_SOURCE: postgres://postgres:postgres@localhost:5432/bugby?sslmode=disable

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: 1.22

      - name: Tidy modules
        run: go mod tidy

      - name: Check go mod tidy state
        run: |
          git diff --exit-code go.mod go.sum

      - name: Run tests
        run: go test ./... -v

      - name: Build
        run: go build -v ./...
